clear; clc; close all;
%%
count_tbl = readtable('/Volumes/PM-HD/FAST_data/MS5_SanityChecks/vary_thresh_unit_counts.xlsx');

figure
tt = tiledlayout(1,2);

nexttile
plot(count_tbl.threshold, ...
     count_tbl.num_units, ...
     'Color',[1 0.7 0.7], ...
     'LineStyle','-', ...
     'LineWidth',3,...
     'Marker','square', 'MarkerFaceColor','auto', ...
     'MarkerSize',8)
xlabel('Detection Threshold')
xlim([min(count_tbl.threshold) max(count_tbl.threshold)])
ylabel('Number of detected units')
set(gca, 'FontSize',18)
grid on
set(gca, 'LineWidth', 1.5)


nexttile
plot(count_tbl.threshold, ...
     count_tbl.num_events./1000, ...
     'Color',[0.7 0.7 1], ...
     'LineStyle','-', ...
     'LineWidth',3,...
     'Marker','square', 'MarkerFaceColor','auto', ...
     'MarkerSize',8)

line(xlim, 74995.*[1 1]./1000, 'Color', 'k')

xlabel('Detection Threshold')
xlim([min(count_tbl.threshold) max(count_tbl.threshold)])
ylabel('Thousands of detected events')

text(min(xlim), 74995./1000, ...
    'Ground truth events for top 8 units', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'FontSize',14)
set(gca, 'FontSize',18)
set(gca, 'LineWidth', 1.5)
grid on